<?php
$page = [
    'home' => 'view/home.php',
    'shome' => 'view/shome.php',
    'login' => 'view/login.php',
    'register' => 'view/register.php',
    'afterfirst' => 'view/afterfirst.php',
    'leaves' => 'view/leaves.php',
    'alogin' => 'view/alogin.php',
    'slogin' => 'view/slogin.php',
    'aafterfirst' => 'view/aafterfirst.php',
    'aleaves' => 'view/aleaves.php',
    'search' => 'view/search.php',
    'sregister' => 'view/sregister.php',
    'logout'=>'view/logout.php',
    'alogout'=>'view/alogout.php',
    'slogout'=>'view/slogout.php',
    'editp' => 'view/editp.php',
    'aedit' => 'view/aedit.php',
    'newrecord' => 'view/newrecord.php',
    'addleave' => 'view/addleave.php',
    'check' => "view/check.php",
    'acheck' => "view/acheck.php",
    'deleterecord' => "view/deleterecord.php",
    'apply' => "view/apply.php",
    'status' => "view/status.php",
    'sapply' => "view/sapply.php",
    'rlogin' => "view/rlogin.php",
    'vclogin' => "view/rlogin.php",
    'dlogin' => "view/dlogin.php",
    'apedit' => "view/apedit.php",
    'updatepost' => "view/updatepost.php",
    'rhome' => "view/rhome.php",
    'dhome' => "view/dhome.php",
    'vchome' => "view/vchome.php"
];

